// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/api/handler"
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/application/user"
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/infrastructure/input/server/config"
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/infrastructure/input/server/http"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.DB) (*http.Server, error) {
	repository, err := ResolveUserRepository(cfg)
	if err != nil {
		return nil, err
	}
	finderAllUseCase := user.NewDefaultFinderAllUseCase(repository)
	finderByIDUseCase := user.NewDefaultFinderByIDUseCase(repository)
	creatorUseCase := user.NewDefaultCreatorUseCase(repository)
	modifierUseCase := user.NewDefaultModifierUseCase(repository)
	deleterUseCase := user.NewDefaultDeleterUseCase(repository)
	userAPI := handler.NewUserAPI(finderAllUseCase, finderByIDUseCase, creatorUseCase, modifierUseCase, deleterUseCase)
	server := http.NewServer(userAPI)
	return server, nil
}
