// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/api/handler"
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/application/usecase"
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/infrastructure/repository"
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/infrastructure/server/config"
	"github.com/josepdcs/go-proposal-hexagonal-arch/internal/infrastructure/server/http"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.Server, error) {
	user := repository.NewUserInMemory()
	userFinderAll := usecase.NewUserFinderAll(user)
	userFinderByID := usecase.NewUserFinderByID(user)
	userCreator := usecase.NewUserCreator(user)
	userModifier := usecase.NewUserModifier(user)
	userDeleter := usecase.NewUserDeleter(user)
	userAPI := handler.NewUserAPI(userFinderAll, userFinderByID, userCreator, userModifier, userDeleter)
	server := http.NewServer(userAPI)
	return server, nil
}
